Fill out circle ci config

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,37 +1,69 @@
 version: 2.1
 
 commands:
+  create-dotenv-file:
+    description: Create .env file for backend project
+    steps:
+      - run:
+          name: Write env vars to .env
+          command: |
+            echo ENVIRONMENT=$ENVIRONMENT > ./backend/.env
+            echo TYPEORM_CONNECTION=$TYPEORM_CONNECTION > ./backend/.env
+            echo TYPEORM_MIGRATIONS_DIR=$TYPEORM_MIGRATIONS_DIR > ./backend/.env
+            echo TYPEORM_ENTITIES=$TYPEORM_ENTITIES > ./backend/.env
+            echo TYPEORM_MIGRATIONS=$TYPEORM_MIGRATIONS > ./backend/.env
+            echo TYPEORM_HOST=$TYPEORM_HOST > ./backend/.env
+            echo TYPEORM_PORT=$TYPEORM_PORT > ./backend/.env
+            echo TYPEORM_USERNAME=$TYPEORM_USERNAME > ./backend/.env
+            echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD > ./backend/.env
+            echo TYPEORM_DATABASE=$TYPEORM_DATABASE > ./backend/.env
+
   destroy-environment:
     description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
     parameters:
-      # Add parameter here   
+      workflowID:
+        type: string
     steps:
       - run:
-          name: Destroy environments
+          name: Print workflow ID to be destroyed
+          when: on_fail
+          command: echo "WorkflowID=${CIRCLE_WORKFLOW_ID}"
+      - run:
+          name: Destroy backend
           when: on_fail
           command: |
-            # Your code here
+            aws s3 rm s3://udapeople-<< parameters.workflowID >> --recursive
+            aws s3 rb s3://udapeople-<< parameters.workflowID >> --force
+            aws cloudformation delete-stack --stack-name backend-<< parameters.workflowID >>
+            exit 1
+      - run:
+          name: Destroy frontend
+          when: on_fail
+          command: |
+            aws cloudformation delete-stack --stack-name frontend-<< parameters.workflowID >>
             exit 1
 
   revert-migrations:
     description: Revert the last migration if successfully run in the current workflow.
     parameters:
-      # Add parameter here     
+      workflowID:
+        type: string
     steps:
       - run:
           name: Revert migrations
-          # Add when this will run
+          when: on_fail
           command: |
             # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
-            SUCCESS = 1
-            if(( $SUCCESS==1 )); 
+            SUCCESS=$(curl -H "token: 7eb3bef9-f1a7-44a1-9ff7-22631e3f0b0e" --request GET https://api.memstash.io/values/DB_MIGRATION_STATUS_<< parameters.workflowID >>)
+            echo $SUCCESS
+            if(( $SUCCESS==1 ));
             then
-            #  cd ~/project/backend
-            #  npm install
-            #  Add revert code here. You can find this in the Getting Started section.
+              cd ~/project/backend # ./backend
+              npm install
+              npm run migration:revert
               exit 1
             fi
-            
+
 jobs:
   build-frontend:
     docker:
@@ -43,7 +75,9 @@ jobs:
       - run:
           name: Build front-end
           command: |
-            # Your code here
+            cd ~/project/frontend #./frontend
+            npm i
+            npm run build
             exit 1
       - save_cache:
           paths: [frontend/node_modules]
@@ -59,209 +93,332 @@ jobs:
       - run:
           name: Back-end build
           command: |
-             # Your code here
-             exit 1
+            cd ~/project/backend
+            npm i
+            npm run build
+            exit 1
       - save_cache:
           paths: [backend/node_modules]
           key: backend-build
 
   test-frontend:
     docker:
-      # Docker image here
+      - image: circleci/node:13.8.0
     steps:
-      # Checkout code from git
-      # Restore from cache
-      # Your job code here
-                
+      - checkout
+      - restore_cache:
+          keys: [frontend-build]
+      - run:
+          name: Test frontend
+          command: |
+            cd ~/project/frontend
+            npm run test
+
   test-backend:
     docker:
-      # Docker image here
+      - image: circleci/node:13.8.0
     steps:
-      # Checkout code from git
-      # Restore from cache
-      # Your job code here
-            
+      - checkout
+      - restore_cache:
+          keys: [backend-build]
+      - run:
+          name: Test backend
+          command: |
+            cd ~/project/backend
+            npm run test
+
   scan-frontend:
     docker:
-      # Docker image here
+      - image: circleci/node:13.8.0
     steps:
-      # Checkout code from git
-      # Restore from cache
-      # Your job code here
+      - checkout
+      - restore_cache:
+          keys: [frontend-build]
+      - run:
+          name: Test frontend
+          command: |
+            cd ~/project/frontend
+            npm audit
 
   scan-backend:
     docker:
-      # Docker image here
+      - image: circleci/node:13.8.0
     steps:
-      # Checkout code from git
-      # Restore from cache
-      # Your job code here
+      - checkout
+      - restore_cache:
+          keys: [backend-build]
+      - run:
+          name: Test backend
+          command: |
+            cd ~/project/backend
+            npm audit
 
   deploy-infrastructure:
     docker:
-      # Docker image here that supports AWS CLI
+      - image: amazon/aws-cli
     steps:
-      # Checkout code from git
+      - checkout
+      - run:
+          name: Install required dependencies
+          command: yum -u install tar gzip
       - run:
           name: Ensure back-end infrastructure exists
           command: |
             aws cloudformation deploy \
               --template-file .circleci/files/backend.yml \
-              #--tags project=your-tag \
-              # --stack-name "your back-end stack name with workflow id" \
-              # --parameter-overrides ID="your workflow id"  
-              exit 1
+              --tags project=backend-${CIRCLE_WORKFLOW_ID} \
+              --stack-name "backend-${CIRCLE_WORKFLOW_ID}" \
+              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID}"
+            exit 1
       - run:
           name: Ensure front-end infrastructure exist
           command: |
             aws cloudformation deploy \
               --template-file .circleci/files/frontend.yml \
-              #--tags project=your-tag \
-              # --stack-name "your front-end stack name with workflow id" \
-              # --parameter-overrides ID="your workflow id"  
-              exit 1
+              --tags project=frontend-${CIRCLE_WORKFLOW_ID} \
+              --stack-name "frontend-${CIRCLE_WORKFLOW_ID}" \
+              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID}"
+            exit 1
+      - run:
+          name: Add backend IP to memstash
+          command: |
+            BACKEND_IP=$(aws ec2 describe-instances \
+              --query "Reservations[*].Instances[*].PublicIpAddress" \
+              --filters "Name=tag:project,Values=backend-${CIRCLE_WORKFLOW_ID}" \
+              --output text)
+            echo "BACKEND_IP=${BACKEND_IP}"
+          curl -H "Content-Type: text/plain" -H "token: 7eb3bef9-f1a7-44a1-9ff7-22631e3f0b0e" --request PUT --data "$BACKEND_IP" https://api.memstash.io/values/BACKEND_IP_${CIRCLE_WORKFLOW_ID}
       - run:
           name: Add back-end ip to ansible inventory
           command: |
-            # Your code here
+            $BACKEND_IP=$(curl -H "token: 7eb3bef9-f1a7-44a1-9ff7-22631e3f0b0e" --request GET https://api.memstash.io/values/BACKEND_IP_${CIRCLE_WORKFLOW_ID}
+            echo $BACKEND_IP >> ~/project/.circleci/ansible/inventory.txt
+            cat ~/project/.circleci/ansible/inventory.txt
             exit 1
       - persist_to_workspace:
           root: ~/
           paths:
             - project/.circleci/ansible/inventory.txt
-      # Here's where you will add some code to rollback on failure      
+      - destroy-environment:
+          workflowID: ${CIRCLE_WORKFLOW_ID}
 
   configure-infrastructure:
     docker:
-      # Docker image here that supports Ansible
+      - image: python:3.7-alpine3.11
     steps:
-      # Checkout code from git
-      # Add ssh keys with fingerprint
-      # attach workspace
+      - checkout
+      - add_ssh_keys:
+          fingerprints:
+            - "@TODO: ssh fingerprint"
+      - attach_workspace:
+          at: .
       - run:
           name: Install dependencies
           command: |
-            # Your code here
+            apk add --update ansible
+            pip install awscli
             exit 1
+      - create-dotenv-file
       - run:
           name: Configure server
           command: |
-            # Your code here
+            cat ~/project/.circleci/ansible/inventory.txt
+            export ANSIBLE_HOST_KEY_CHECKING=false
+            ansible-playbook -i ~/project/.circleci/ansible/inventory.txt ~/project/.circleci/ansible/configure-server.yml
             exit 1
-      # Here's where you will add some code to rollback on failure      
+      - destroy-environment:
+          workflowID: ${CIRCLE_WORKFLOW_ID}
 
   run-migrations:
     docker:
-      # Docker image here that supports NodeJS
+      - image: circleci/node:13.8.0
     steps:
-      # Checkout code from git
+      - checkout
+        restore_cache:
+          keys: [backend-build]
+        attach_workspace:
+          at: .
+        create-dotenv-file
       - run:
           name: Run migrations
           command: |
-            # Your code here
+            cd ~/project/backend
+            npm run migrations > migrations_log.txt
+            cat ./migrations_log.txt
             exit 1
       - run:
           name: Send migration results to memstash
           command: |
-            # Your code here
+            if grep "has been executed successfull" ~/project/backend/migrations_log.txt;
+            then
+              echo "Successful"
+              curl -H "Content-Type: text/plain" -H "token: 7eb3bef9-f1a7-44a1-9ff7-22631e3f0b0e" --request PUT --data "success" https://api.memstash.io/values/DB_MIGRATION_STATUS_${CIRCLE_WORKFLOW_ID}
+            else
+              echo "Failure"
+              curl -H "Content-Type: text/plain" -H "token: 7eb3bef9-f1a7-44a1-9ff7-22631e3f0b0e" --request PUT --data "failure" https://api.memstash.io/values/DB_MIGRATION_STATUS_${CIRCLE_WORKFLOW_ID}
+            fi
             exit 1
-     # Here's where you will add some code to rollback on failure      
+      - destroy-environment:
+          workflowID: ${CIRCLE_WORKFLOW_ID}
 
   deploy-frontend:
     docker:
-      # Docker image here that supports AWS CLI
+      - image: amazon/aws-cli
     steps:
-      # Checkout code from git
+      - checkout
       - run:
           name: Install dependencies
           command: |
-            # your code here
+            yum install -y tar gzip curl
+            curl -sL https://rpm.nodesource.com/setup_10.x | bash -
+            yum install -y nodejs
       - run:
           name: Get backend url
           command: |
             # your code here
+            $BACKEND_IP=$(curl -H "token: 7eb3bef9-f1a7-44a1-9ff7-22631e3f0b0e" --request GET https://api.memstash.io/values/BACKEND_IP_${CIRCLE_WORKFLOW_ID}
             export API_URL="http://${BACKEND_IP}:3030"
             echo "${API_URL}"
+            echo ENVIRONMENT=production > ~/project/frontend/.env
+            echo API_URL=${API_URL} > ~/project/frontend/.env
+            cat ~/project/frontend.env
+      - run:
+          name: Build frontend
+          command: |
+            cd ~/project/frontend
+            npm i
+            npm run build
       - run:
           name: Deploy frontend objects
           command: |
-            # your code here
-      # Here's where you will add some code to rollback on failure      
-                    
+            aws s3 cp ~/project/frontend/dist "s3://udapeople-${CIRCLE_WORKFLOW_ID}"
+      - persist_to_workspace:
+          root:
+          paths:
+            - ~/project/frontend/dist
+      - destroy-environment:
+          workflowID: ${CIRCLE_WORKFLOW_ID}
+      - revert-migrations:
+          workflowID: ${CIRCLE_WORKFLOW_ID}
+
   deploy-backend:
     docker:
-      # Docker image here that supports Ansible
+      - image: python:3.7-alpine3.11
     steps:
-      # Checkout code from git
-      # Add ssh keys with fingerprint
-      # attach workspace
+      - checkout
+      - add_ssh_keys:
+          fingerprints:
+            - "@TODO"
+      - attach_workspace:
+          at: .
+      - restore_cache:
+          keys: [backend-build]
       - run:
           name: Install dependencies
           command: |
-            # your code here
+            apk add --update ansible
+            apk add --no-cache curl
+            apk add --no-cache openssh-client
+            apk add --no-cache --upgrade bash
+            pip install awscli
+      - create-dotenv-file
       - run:
           name: Deploy backend
           command: |
-            # your code here
-      # Here's where you will add some code to rollback on failure  
+            tar czf backend.tar.gz backend
+            export ANSIBLE_HOST_KEY_CHECKING=false
+            ansible-playbook -i ./.circleci/ansible/inventory.txt
+      - destroy-environment:
+          workflowID: ${CIRCLE_WORKFLOW_ID}
+      - revert-migrations:
+          workflowID: ${CIRCLE_WORKFLOW_ID}
 
   smoke-test:
     docker:
-      # Lightweight Docker image 
+      # Lightweight Docker image
+      - image: alpine:latest
     steps:
-      # Checkout code from git
+      - checkout
       - run:
           name: Install dependencies
           command: |
-            # your code here
-      - run:
-          name: Get backend url
-          command: |
-            # your code here
+            apk --no-cache add curl
+            apk add --update npm
+            apk add --no-cache python3 py3-pip
+            pip3 install --upgrade pip
+            pip install awscli
+      - create-dotenv-file
       - run:
           name: Backend smoke test.
           command: |
-            # your code here
+            $BACKEND_IP=$(curl -H "token: 7eb3bef9-f1a7-44a1-9ff7-22631e3f0b0e" --request GET https://api.memstash.io/values/BACKEND_IP_${CIRCLE_WORKFLOW_ID}
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo $API_URL
+            curl -s "${API_URL}/api/status" -v
       - run:
           name: Frontend smoke test.
           command: |
-            # your code here
-      # Here's where you will add some code to rollback on failure  
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID}.s3-website-eu-central-1.amazonaws.com"
+            curl -s $URL | grep "Welcome"
+      - destroy-environment:
+          workflowID: ${CIRCLE_WORKFLOW_ID}
+      - revert-migrations:
+          workflowID: ${CIRCLE_WORKFLOW_ID}
 
   cloudfront-update:
     docker:
-      # Docker image here that supports AWS CLI
+      - image: amazon/aws-cli
     steps:
-      # Checkout code from git
+      - checkout
       - run:
           name: Install dependencies
           command: |
-            # your code here
+            yum install -y tar gzip curl
+            curl -sL https://rpm.nodesource.com/setup_10.x | bash -
+            yum install -y nodejs
+      - run:
+          name: Save old workflow ID to memstash
+          command: |
+            OLD_WORKFLOW_ID=$(aws cloudformation list-exports \
+              --query "Exports[?Name==\`WorkflowID\`].Value" \
+              --no-paginate \
+              --output text)
+            echo $OLD_WORKFLOW_ID
+          curl -H "Content-Type: text/plain" -H "token: 7eb3bef9-f1a7-44a1-9ff7-22631e3f0b0e" --request PUT --date "$OLD_WORKFLOW_ID" https://api.memstash.io/values/OLD_WORKFLOW_ID
       - run:
           name: Update cloudfront distribution
           command: |
-            # your code here
-      # Here's where you will add some code to rollback on failure  
+            aws cloudformation deploy \
+              --template-file ./.circleci/files/cloudfront.yml \
+              --tags project=udapeople \
+              --stack-name "udapeople-cloudfront-production" \
+              --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID}
+      - destroy-environment:
+          workflowID: ${CIRCLE_WORKFLOW_ID}
+      - revert-migrations:
+          workflowID: ${CIRCLE_WORKFLOW_ID}
 
 cleanup:
     docker:
-      # Docker image here
+      - image: amazon/aws-cli
     steps:
-      # Checkout code from git
+      - checkout
       - run:
           name: Get old stack workflow id
           command: |
             # your code here
-            export OldWorkflowID="the id here"
-            export STACKS=[] #put the list of stacks here
+            export OldWorkflowID=$(curl -H "token: 7eb3bef9-f1a7-44a1-9ff7-22631e3f0b0e" --request GET https://api.memstash.io/values/OLD_WORKFLOW_ID)
+            export STACKS=[ ${CIRLCE_WORKFLOW_ID}, $OldWorkflowID ] #put the list of stacks here
       - run:
           name: Remove old stacks and files
           command: |
             if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
             then
-              # your code here
+              aws s3 rm "s3://udapeople-${OLD_WORKFLOW_ID}"
+              aws cloudformation delete-stack --stack-name "frontend-${OLD_WORKFLOW_ID}"
+              aws cloudformation delete-stack --stack-name "backend-${OLD_WORKFLOW_ID}"
             fi
-            
+
 
 workflows:
   default:
